<?php

/**
 * CategoricalElicitation
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    elicitor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CategoricalElicitation extends BaseCategoricalElicitation {

    public function getProgress() {
        $complete = 0;
        if ($this->read_briefing_document == 1) {
            $complete++;
        }
        $stuff = json_decode($this->results);
        $edited = false;
        if ($stuff != null) {
            foreach ($stuff as $k => $v) {
                if ($v > 0) {
                    $edited = true;
                    break;
                }
            }
        }
        if ($edited) {
            $complete++;
        }
        return $complete / 2 * 100;
    }

    public function getResultsArray() {
        $res = json_decode($this->results);
        return $res;
    }

    public function getNumberOfBeans() {
        $result = 0;
        $categories = json_decode($this->results);
        if ($categories != null) {
            foreach ($categories as $k => $v) {
                if($k !== '_empty_') {
                    $result += $v;
                }

            }
        }
        return $result;
    }

    public function getCategories() {
        $categories = explode(',', $this->getVariable()->getVariableParameters());

        $res = array();
        foreach($categories as $c) {
            $res[] = trim($c);
        }

        return $res;
    }

}