<?php

/**
 * ContinuousElicitation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    elicitor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ContinuousElicitation extends BaseContinuousElicitation {

    public function getProgress() {
        $complete = 0;
        
       
        if ($this->read_briefing_document == 1) {
            $complete++;
        }
        if (!is_null($this->minimum)) {
            $complete++;
        }
        if (!is_null($this->maximum)) {
            $complete++;
        }
        if (!is_null($this->lower)) {
            $complete++;
        }
        if (!is_null($this->median)) {
            $complete++;
        }
        if (!is_null($this->upper)) {
            $complete++;
        }
        return round($complete / 6 * 100);
    }

    public function toJSON() {
        $params = $this->processParameters($this->getParameters(), $this->getName());
        $pdf = array('name' => $this->getName(), 'parameters' => $params);
        $output = array('name' => $pdf['name'], 'parameters' => $pdf['parameters']);
        return json_encode($output);
    }

    private function processParameters($parameters, $dist_name) {
        $params = array();
        $splits = array();
        foreach($paramaters as $p) {
            $splits[] = $p->getValue();
        }
        if (sizeof($splits) == 1) {
            $params['dof'] = $splits[0];
        } else {
            // not a student-t variant
            if ($dist_name == 'Normal') {
                // normal distribution
                $params['mean'] = $splits[0];
                $params['variance'] = $splits[1];
            } else if ($dist_name == 'LogNormal') {
                $params['location'] = $splits[0];
                $params['scale'] = $splits[1];
            } else if ($dist_name == 'Beta') {
                // beta distribution
                $params['alpha'] = $splits[0];
                $params['beta'] = $splits[1];
            } else if ($dist_name == 'Gamma') {
                // gamma
                $params['shape'] = $splits[0];
                $params['scale'] = 1/$splits[1];
            } else if ($dist_name == 'StudentT') {
                // student t
                $params['dof'] = $splits[0];
                $params['ncp'] = $splits[1];
            }
        }
        return $params;
    }

}