<?php

/**
 * DistributionParameterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DistributionParameterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DistributionParameterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DistributionParameter');
    }
}