<?php

/**
 * DistributionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DistributionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DistributionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Distribution');
    }
}