<?php

/**
 * ElicitationProblemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ElicitationProblemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ElicitationProblemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ElicitationProblem');
    }
}