<?php

/**
 * SpatialElicitation
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    elicitor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SpatialElicitation extends BaseSpatialElicitation
{
    public function getProgress() {
        $complete = 0;


        if ($this->read_briefing_document == 1) {
            $complete++;
        }
        if (!is_null($this->minimum)) {
            $complete++;
        }
        if (!is_null($this->maximum)) {
            $complete++;
        }
        if (!is_null($this->lower)) {
            $complete++;
        }
        if (!is_null($this->median)) {
            $complete++;
        }
        if (!is_null($this->upper)) {
            $complete++;
        }
        return round($complete / 6 * 100);
    }
}
