<?php

/**
 * SpatialElicitationTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpatialElicitationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpatialElicitationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SpatialElicitation');
    }


    public function findByExpertAndTask($expert_id, $task_id)
    {
        $q = $this->createQuery('se')
                        ->where('se.expert_id = ?', $expert_id)
                        ->andWhere('se.variable_id = ?', $task_id);
        return $q->fetchOne();
    }
}