<?php

/**
 * UserExpertTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserExpertTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object UserExpertTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('UserExpert');
    }

    public function findSpecific($user_id, $expert_id) {
        $q = $this->createQuery('ue')
                        ->where('ue.user_id = ?', $user_id)
                        ->andWhere('ue.expert_id = ?', $expert_id);
        return $q->fetchOne();
    }

}