<?php

/**
 * VariableExpertTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VariableExpertTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VariableExpertTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VariableExpert');
    }

}