<?php

/**
 * VariableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VariableTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VariableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Variable');
    }

    public function findOneByHash($hash) {
        $q = $this->createQuery()
                ->where('md5(id) = ?', $hash);
        return $q->fetchOne();
    }
}