<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }

    public function findByHash($hash) {
        $q = $this->createQuery('u')
                        ->select('u.*')
                        ->where('md5(u.username) = ?', $hash);
        return $q->fetchOne();
    }
}